services:
  - type: web
    name: fastapi-cap
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-cap-db
          property: connectionString
    healthCheckPath: /docs

databases:
  - name: fastapi-cap-db
    databaseName: fastapi_cap
    user: fastapi_user
    plan: free
